### PR TITLE
Feature library

### PR DESCRIPTION
**Pull request by billodiallo**
In this project we created a simple library using JavaScript and finished the following milestones:
- Basic initial setups and linter configurations.
-  Set the project with skeleton HTML/CSS and JS files.
 - Add a function to the script that can take user’s input and store the new book objects into an array.
 - Write a function that loops through the array and displays each book on the page
 - Add a “NEW BOOK” button that brings up a form allowing users to input the details for the new book
-  Add a button on each book’s display to remove the book from the library

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

Just few updates and we are good.

* [x] In your scripts.js file, there are lots of disabled and enable eslint comments, remove the comments and fix any associated errors.
* [x] On line 42 in scripts.js, remove the commented line of code.

[**Optional**] 
* [x] It would be nice if the read status is implemented with the HTML input type of checkbox.
* [x] I should not be able to submit the create book form with empty fields.
* [x] It would be nice if the values of the book created, align with the table heading. I will leave an image below for reference.

align

#### That's it, make these changes, then submit another form for a code review.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Review by SmithVyne — CHANGES_REQUESTED** [review]
## Changes Required 🤕 👍 
Your 'Add Book' button isn't currently working. You may want to figure out why and request another code review. 

You can reach out to me on slack, **@SmithVyne**, if you have any other questions

**Comment by billodiallo** [comment]
Thanks for the review
add Button issue fixed

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @billodiallo and @wintan1418  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

 _**P.S: Add the `node_module` to the `.gitignore` file.**_

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
